namespace Lyra.ManagedCodecs.Tests.Heif;

internal static class HeifSequenceFixtures
{
    /// <summary>avifenc -l, durations 10, 20 and 5 at 100 ticks a second, looping forever; alpha in an auxv track.</summary>
    public const string Avif =
        "AAAALGZ0eXBhdmlzAAAAAGF2aWZhdmlzbXNmMWlzbzhtaWYxbWlhZk1BMUEAAAGGbWV0YQAAAAAAAAAhaGRscgAAAAAAAAAAcGljdAAAAAAAAAAAAAAAAAAA" +
        "AAAOcGl0bQAAAAAAAQAAACxpbG9jAAAAAEQAAAIAAQAAAAEAAAdmAAAALQACAAAAAQAABycAAAAaAAAAQmlpbmYAAAAAAAIAAAAaaW5mZQIAAAAAAQAAYXYw" +
        "MUNvbG9yAAAAABppbmZlAgAAAAACAABhdjAxQWxwaGEAAAAAGmlyZWYAAAAAAAAADmF1eGwAAgABAAEAAADDaXBycAAAAJ1pcGNvAAAAFGlzcGUAAAAAAAAA" +
        "EAAAAAwAAAAQcGl4aQAAAAADCAgIAAAADGF2MUOBIAAAAAAAE2NvbHJuY2x4AAEADQAAgAAAAA5waXhpAAAAAAEIAAAADGF2MUOBABwAAAAAOGF1eEMAAAAA" +
        "dXJuOm1wZWc6bXBlZ0I6Y2ljcDpzeXN0ZW1zOmF1eGlsaWFyeTphbHBoYQAAAAAeaXBtYQAAAAAAAAACAAEEAQKDBAACBAEFhgcAAAVtbW9vdgAAAHhtdmhk" +
        "AQAAAAAAAADm6ZZ3AAAAAObplncAAABk//////////8AAQAAAQAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAlp0cmFrAAAAaHRraGQBAAABAAAAAObplncAAAAA5umWdwAAAAEAAAAA//////////8AAAAAAAAAAAAAAAAAAAAA" +
        "AAEAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAABAAAAAABAAAAAMAAAAAAAsZWR0cwAAACRlbHN0AQAAAQAAAAEAAAAAAAAAIwAAAAAAAAAAAAEAAAAA" +
        "Ab5tZGlhAAAALG1kaGQBAAAAAAAAAObplncAAAAA5umWdwAAAGQAAAAAAAAAI1XEAAAAAAAhaGRscgAAAAAAAAAAcGljdAAAAAAAAAAAAAAAAAAAAAFpbWlu" +
        "ZgAAABR2bWhkAAAAAQAAAAAAAAAAAAAAJGRpbmYAAAAcZHJlZgAAAAAAAAABAAAADHVybCAAAAABAAABKXN0YmwAAACVc3RzZAAAAAAAAAABAAAAhWF2MDEA" +
        "AAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAEAAMAEgAAABIAAAAAAAAAAEKQU9NIENvZGluZwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAY//8AAAAMYXYxQ4EgAAAA" +
        "AAATY29scm5jbHgAAQANAACAAAAAEGNjc3QAAAAAfAAAAAAAAChzdHRzAAAAAAAAAAMAAAABAAAACgAAAAEAAAAUAAAAAQAAAAUAAAAcc3RzYwAAAAAAAAAB" +
        "AAAAAQAAAAMAAAABAAAAIHN0c3oAAAAAAAAAAAAAAAMAAAAtAAAAQAAAAEkAAAAUc3RjbwAAAAAAAAABAAAHZgAAABRzdHNzAAAAAAAAAAEAAAABAAACk3Ry" +
        "YWsAAABodGtoZAEAAAEAAAAA5umWdwAAAADm6ZZ3AAAAAgAAAAD//////////wAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAA" +
        "AAAAAEAAAAAAEAAAAAwAAAAAABR0cmVmAAAADGF1eGwAAAABAAAALGVkdHMAAAAkZWxzdAEAAAEAAAABAAAAAAAAACMAAAAAAAAAAAABAAAAAAHjbWRpYQAA" +
        "ACxtZGhkAQAAAAAAAADm6ZZ3AAAAAObplncAAABkAAAAAAAAACNVxAAAAAAAIWhkbHIAAAAAAAAAAGF1eHYAAAAAAAAAAAAAAAAAAAABjm1pbmYAAAAUdm1o" +
        "ZAAAAAEAAAAAAAAAAAAAACRkaW5mAAAAHGRyZWYAAAAAAAAAAQAAAAx1cmwgAAAAAQAAAU5zdGJsAAAAunN0c2QAAAAAAAAAAQAAAKphdjAxAAAAAAAAAAEA" +
        "AAAAAAAAAAAAAAAAAAAAABAADABIAAAASAAAAAAAAAABCkFPTSBDb2RpbmcAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGP//AAAADGF2MUOBABwAAAAAEGNjc3QA" +
        "AAAAfAAAAAAAADhhdXhpAAAAAHVybjptcGVnOm1wZWdCOmNpY3A6c3lzdGVtczphdXhpbGlhcnk6YWxwaGEAAAAAKHN0dHMAAAAAAAAAAwAAAAEAAAAKAAAA" +
        "AQAAABQAAAABAAAABQAAABxzdHNjAAAAAAAAAAEAAAABAAAAAwAAAAEAAAAgc3RzegAAAAAAAAAAAAAAAwAAABoAAAAVAAAAEAAAABRzdGNvAAAAAAAAAAEA" +
        "AAcnAAAAFHN0c3MAAAAAAAAAAQAAAAEAAAD9bWRhdBIACgkAAAABn9m18lQyCxQAIACMnLwTmy/AEgAyETIB4EAAAD0ACAAAAQsGq2+wEgAyDDMCAIIAAAaA" +
        "BAB7UBIACgwgAAABn9m18kBDQAgyGxAAgAA2xCZtxgb+mii8UE4lR1x5PSI5zGJUgBIAMjwwA8CAAABGgAEAwdw/D0eWvtcqc9xxU/7ODy67XImpHb/wzd//" +
        "4LYP/GSAV8kGRChxaGsjbnS38WCQDu8SADJFMAQBBAAARoABAMd6TeGN7npavG4BQiXjVlyyBmBoIKkI7eZuXNgH0D6sd5bUCJXIpisYEgODPVpaa+MvF8hH" +
        "YgCA3RIM";

    /// <summary><see cref="Avif"/> with its alpha track's handler patched to "pict", as libavif once wrote it.</summary>
    public const string AvifOldAlpha =
        "AAAALGZ0eXBhdmlzAAAAAGF2aWZhdmlzbXNmMWlzbzhtaWYxbWlhZk1BMUEAAAGGbWV0YQAAAAAAAAAhaGRscgAAAAAAAAAAcGljdAAAAAAAAAAAAAAAAAAA" +
        "AAAOcGl0bQAAAAAAAQAAACxpbG9jAAAAAEQAAAIAAQAAAAEAAAdmAAAALQACAAAAAQAABycAAAAaAAAAQmlpbmYAAAAAAAIAAAAaaW5mZQIAAAAAAQAAYXYw" +
        "MUNvbG9yAAAAABppbmZlAgAAAAACAABhdjAxQWxwaGEAAAAAGmlyZWYAAAAAAAAADmF1eGwAAgABAAEAAADDaXBycAAAAJ1pcGNvAAAAFGlzcGUAAAAAAAAA" +
        "EAAAAAwAAAAQcGl4aQAAAAADCAgIAAAADGF2MUOBIAAAAAAAE2NvbHJuY2x4AAEADQAAgAAAAA5waXhpAAAAAAEIAAAADGF2MUOBABwAAAAAOGF1eEMAAAAA" +
        "dXJuOm1wZWc6bXBlZ0I6Y2ljcDpzeXN0ZW1zOmF1eGlsaWFyeTphbHBoYQAAAAAeaXBtYQAAAAAAAAACAAEEAQKDBAACBAEFhgcAAAVtbW9vdgAAAHhtdmhk" +
        "AQAAAAAAAADm6ZZ3AAAAAObplncAAABk//////////8AAQAAAQAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAlp0cmFrAAAAaHRraGQBAAABAAAAAObplncAAAAA5umWdwAAAAEAAAAA//////////8AAAAAAAAAAAAAAAAAAAAA" +
        "AAEAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAABAAAAAABAAAAAMAAAAAAAsZWR0cwAAACRlbHN0AQAAAQAAAAEAAAAAAAAAIwAAAAAAAAAAAAEAAAAA" +
        "Ab5tZGlhAAAALG1kaGQBAAAAAAAAAObplncAAAAA5umWdwAAAGQAAAAAAAAAI1XEAAAAAAAhaGRscgAAAAAAAAAAcGljdAAAAAAAAAAAAAAAAAAAAAFpbWlu" +
        "ZgAAABR2bWhkAAAAAQAAAAAAAAAAAAAAJGRpbmYAAAAcZHJlZgAAAAAAAAABAAAADHVybCAAAAABAAABKXN0YmwAAACVc3RzZAAAAAAAAAABAAAAhWF2MDEA" +
        "AAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAEAAMAEgAAABIAAAAAAAAAAEKQU9NIENvZGluZwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAY//8AAAAMYXYxQ4EgAAAA" +
        "AAATY29scm5jbHgAAQANAACAAAAAEGNjc3QAAAAAfAAAAAAAAChzdHRzAAAAAAAAAAMAAAABAAAACgAAAAEAAAAUAAAAAQAAAAUAAAAcc3RzYwAAAAAAAAAB" +
        "AAAAAQAAAAMAAAABAAAAIHN0c3oAAAAAAAAAAAAAAAMAAAAtAAAAQAAAAEkAAAAUc3RjbwAAAAAAAAABAAAHZgAAABRzdHNzAAAAAAAAAAEAAAABAAACk3Ry" +
        "YWsAAABodGtoZAEAAAEAAAAA5umWdwAAAADm6ZZ3AAAAAgAAAAD//////////wAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAA" +
        "AAAAAEAAAAAAEAAAAAwAAAAAABR0cmVmAAAADGF1eGwAAAABAAAALGVkdHMAAAAkZWxzdAEAAAEAAAABAAAAAAAAACMAAAAAAAAAAAABAAAAAAHjbWRpYQAA" +
        "ACxtZGhkAQAAAAAAAADm6ZZ3AAAAAObplncAAABkAAAAAAAAACNVxAAAAAAAIWhkbHIAAAAAAAAAAHBpY3QAAAAAAAAAAAAAAAAAAAABjm1pbmYAAAAUdm1o" +
        "ZAAAAAEAAAAAAAAAAAAAACRkaW5mAAAAHGRyZWYAAAAAAAAAAQAAAAx1cmwgAAAAAQAAAU5zdGJsAAAAunN0c2QAAAAAAAAAAQAAAKphdjAxAAAAAAAAAAEA" +
        "AAAAAAAAAAAAAAAAAAAAABAADABIAAAASAAAAAAAAAABCkFPTSBDb2RpbmcAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGP//AAAADGF2MUOBABwAAAAAEGNjc3QA" +
        "AAAAfAAAAAAAADhhdXhpAAAAAHVybjptcGVnOm1wZWdCOmNpY3A6c3lzdGVtczphdXhpbGlhcnk6YWxwaGEAAAAAKHN0dHMAAAAAAAAAAwAAAAEAAAAKAAAA" +
        "AQAAABQAAAABAAAABQAAABxzdHNjAAAAAAAAAAEAAAABAAAAAwAAAAEAAAAgc3RzegAAAAAAAAAAAAAAAwAAABoAAAAVAAAAEAAAABRzdGNvAAAAAAAAAAEA" +
        "AAcnAAAAFHN0c3MAAAAAAAAAAQAAAAEAAAD9bWRhdBIACgkAAAABn9m18lQyCxQAIACMnLwTmy/AEgAyETIB4EAAAD0ACAAAAQsGq2+wEgAyDDMCAIIAAAaA" +
        "BAB7UBIACgwgAAABn9m18kBDQAgyGxAAgAA2xCZtxgb+mii8UE4lR1x5PSI5zGJUgBIAMjwwA8CAAABGgAEAwdw/D0eWvtcqc9xxU/7ODy67XImpHb/wzd//" +
        "4LYP/GSAV8kGRChxaGsjbnS38WCQDu8SADJFMAQBBAAARoABAMd6TeGN7npavG4BQiXjVlyyBmBoIKkI7eZuXNgH0D6sd5bUCJXIpisYEgODPVpaa+MvF8hH" +
        "YgCA3RIM";

    /// <summary>avifenc -l of frames 3 then 1, one tick each at 100 a second, played three times.</summary>
    public const string AvifThreePlays =
        "AAAALGZ0eXBhdmlzAAAAAGF2aWZhdmlzbXNmMWlzbzhtaWYxbWlhZk1BMUEAAAGGbWV0YQAAAAAAAAAhaGRscgAAAAAAAAAAcGljdAAAAAAAAAAAAAAAAAAA" +
        "AAAOcGl0bQAAAAAAAQAAACxpbG9jAAAAAEQAAAIAAQAAAAEAAAcyAAAAJwACAAAAAQAABv8AAAAZAAAAQmlpbmYAAAAAAAIAAAAaaW5mZQIAAAAAAQAAYXYw" +
        "MUNvbG9yAAAAABppbmZlAgAAAAACAABhdjAxQWxwaGEAAAAAGmlyZWYAAAAAAAAADmF1eGwAAgABAAEAAADDaXBycAAAAJ1pcGNvAAAAFGlzcGUAAAAAAAAA" +
        "EAAAAAwAAAAQcGl4aQAAAAADCAgIAAAADGF2MUOBIAAAAAAAE2NvbHJuY2x4AAEADQAAgAAAAA5waXhpAAAAAAEIAAAADGF2MUOBABwAAAAAOGF1eEMAAAAA" +
        "dXJuOm1wZWc6bXBlZ0I6Y2ljcDpzeXN0ZW1zOmF1eGlsaWFyeTphbHBoYQAAAAAeaXBtYQAAAAAAAAACAAEEAQKDBAACBAEFhgcAAAVFbW9vdgAAAHhtdmhk" +
        "AQAAAAAAAADm6ZZ3AAAAAObplncAAABkAAAAAAAAAAYAAQAAAQAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAkZ0cmFrAAAAaHRraGQBAAABAAAAAObplncAAAAA5umWdwAAAAEAAAAAAAAAAAAAAAYAAAAAAAAAAAAAAAAAAAAA" +
        "AAEAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAABAAAAAABAAAAAMAAAAAAAsZWR0cwAAACRlbHN0AQAAAQAAAAEAAAAAAAAAAgAAAAAAAAAAAAEAAAAA" +
        "AaptZGlhAAAALG1kaGQBAAAAAAAAAObplncAAAAA5umWdwAAAGQAAAAAAAAAAlXEAAAAAAAhaGRscgAAAAAAAAAAcGljdAAAAAAAAAAAAAAAAAAAAAFVbWlu" +
        "ZgAAABR2bWhkAAAAAQAAAAAAAAAAAAAAJGRpbmYAAAAcZHJlZgAAAAAAAAABAAAADHVybCAAAAABAAABFXN0YmwAAACVc3RzZAAAAAAAAAABAAAAhWF2MDEA" +
        "AAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAEAAMAEgAAABIAAAAAAAAAAEKQU9NIENvZGluZwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAY//8AAAAMYXYxQ4EgAAAA" +
        "AAATY29scm5jbHgAAQANAACAAAAAEGNjc3QAAAAAfAAAAAAAABhzdHRzAAAAAAAAAAEAAAACAAAAAQAAABxzdHNjAAAAAAAAAAEAAAABAAAAAgAAAAEAAAAc" +
        "c3RzegAAAAAAAAAAAAAAAgAAACcAAABOAAAAFHN0Y28AAAAAAAAAAQAABzIAAAAUc3RzcwAAAAAAAAABAAAAAQAAAn90cmFrAAAAaHRraGQBAAABAAAAAObp" +
        "lncAAAAA5umWdwAAAAIAAAAAAAAAAAAAAAYAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAABAAAAAABAAAAAMAAAAAAAU" +
        "dHJlZgAAAAxhdXhsAAAAAQAAACxlZHRzAAAAJGVsc3QBAAABAAAAAQAAAAAAAAACAAAAAAAAAAAAAQAAAAABz21kaWEAAAAsbWRoZAEAAAAAAAAA5umWdwAA" +
        "AADm6ZZ3AAAAZAAAAAAAAAACVcQAAAAAACFoZGxyAAAAAAAAAABhdXh2AAAAAAAAAAAAAAAAAAAAAXptaW5mAAAAFHZtaGQAAAABAAAAAAAAAAAAAAAkZGlu" +
        "ZgAAABxkcmVmAAAAAAAAAAEAAAAMdXJsIAAAAAEAAAE6c3RibAAAALpzdHNkAAAAAAAAAAEAAACqYXYwMQAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAQAAwA" +
        "SAAAAEgAAAAAAAAAAQpBT00gQ29kaW5nAAAAAAAAAAAAAAAAAAAAAAAAAAAAABj//wAAAAxhdjFDgQAcAAAAABBjY3N0AAAAAHwAAAAAAAA4YXV4aQAAAAB1" +
        "cm46bXBlZzptcGVnQjpjaWNwOnN5c3RlbXM6YXV4aWxpYXJ5OmFscGhhAAAAABhzdHRzAAAAAAAAAAEAAAACAAAAAQAAABxzdHNjAAAAAAAAAAEAAAABAAAA" +
        "AgAAAAEAAAAcc3RzegAAAAAAAAAAAAAAAgAAABkAAAAaAAAAFHN0Y28AAAAAAAAAAQAABv8AAAAUc3RzcwAAAAAAAAABAAAAAQAAALBtZGF0EgAKCQAAAAGf" +
        "2bXyVDIKEACAAAAeFYekfhIAMhYwA8CAAAB6ABAAAvV+l2V1xYf2OZPgEgAKDCAAAAGf2bXyQENACDIVEACAAAAUubjA39NESvEftW61NmPzEgAySjADwIAA" +
        "AEaAAQAbvhLUdnz4DzQjQxuEjYq4lwLps2aj8TzNf+MmISPdC4kF7sIdovSDqZUYjoF+CReSZkW5jY5i1W6CfAltI+8g";

    /// <summary>heif-enc -S of the three frames at 64x48, coded by x265 as 64x64; 100 ms each, looping forever.</summary>
    public const string Hevc =
        "AAAAKGZ0eXBoZXZjAAAAAG1pZjFoZWljbWlhZm1zZjFpc29taGV2YwAABdRtb292AAAAeG12aGQBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGT//////////wAB" +
        "AAABAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADAAACknRyYWsAAABo" +
        "dGtoZAEAAAcAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAD//////////wAAAAAAAAAAAAAAAAEAAAAAAQAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAEAA" +
        "AAAAQAAAADAAAAAAAf5tZGlhAAAAIG1kaGQAAAAAAAAAAAAAAAAAAABkAAAAHlXLAAAAAAAhaGRscgAAAAAAAAAAcGljdAAAAAAAAAAAAAAAAAAAAAG1bWlu" +
        "ZgAAACRkaW5mAAAAHGRyZWYAAAAAAAAAAQAAAAx1cmwgAAAAAQAAAXVzdGJsAAAA7XN0c2QAAAAAAAAAAQAAAN1odmMxAAAAAAAAAAEAAAAAAAAAAAAAAAAA" +
        "AAAAAEAAMABIAAAASAAAAAAAAAABBEhFVkMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGP//AAAAd2h2Y0MBAWAAAAAAAAAAAAAe8AD8/fj4AAAPA2AA" +
        "AQAYQAEMAf//AWAAAAMAkAAAAwAAAwAeloCQYQABACtCAQEBYAAAAwCQAAADAAADAB6gIIEFllq5Ka5uAhoMCAAAAwMgAAADAFBAYgABAAZEAcFz0IkAAAAQ" +
        "Y2NzdAAAAADAAAAAAAAAGHN0dHMAAAAAAAAAAQAAAAMAAAAKAAAAHHN0c2MAAAAAAAAAAQAAAAEAAAADAAAAAQAAACBzdHN6AAAAAAAAAAAAAAADAAAAmAAA" +
        "AFwAAAAhAAAAFHN0Y28AAAAAAAAAAQAACb0AAAAYc3RzcwAAAAAAAAACAAAAAQAAAAMAAAAUdm1oZAAAAAEAAAAAAAAAAAAAACRlZHRzAAAAHGVsc3QAAAAB" +
        "AAAAAQAAAB4AAAAAAAEAAAAAAsJ0cmFrAAAAaHRraGQBAAAHAAAAAAAAAAAAAAAAAAAAAAAAAAIAAAAA//////////8AAAAAAAAAAAAAAAABAAAAAAEAAAAA" +
        "AAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAABAAAAAAEAAAAAwAAAAAAIabWRpYQAAACBtZGhkAAAAAAAAAAAAAAAAAAAAZAAAAB5VywAAAAAAIWhkbHIAAAAA" +
        "AAAAAGF1eHYAAAAAAAAAAAAAAAAAAAAB0W1pbmYAAAAkZGluZgAAABxkcmVmAAAAAAAAAAEAAAAMdXJsIAAAAAEAAAGRc3RibAAAAQ1zdHNkAAAAAAAAAAEA" +
        "AAD9aHZjMQAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAABAADAASAAAAEgAAAAAAAAAAQRIRVZDAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABj//wAAAHBo" +
        "dmNDAQQIAAAAAAAAAAAAHvAA/Pz4+AAADwNgAAEAF0ABDAH//wQIAAADAJ/IAAADAAAeloCQYQABACVCAQEECAAAAwCfyAAAAwAAHsCCBBZZauSmubAgAAAM" +
        "gAAAAwFBYgABAAZEAcFz0IkAAAAQY2NzdAAAAADAAAAAAAAAJ2F1eGkAAAAAdXJuOm1wZWc6aGV2YzoyMDE1OmF1eGlkOjEAAAAAGHN0dHMAAAAAAAAAAQAA" +
        "AAMAAAAKAAAAHHN0c2MAAAAAAAAAAQAAAAEAAAADAAAAAQAAACBzdHN6AAAAAAAAAAAAAAADAAAArgAAABcAAAARAAAAFHN0Y28AAAAAAAAAAQAACtIAAAAU" +
        "c3RzcwAAAAAAAAABAAAAAQAAABR2bWhkAAAAAQAAAAAAAAAAAAAAFHRyZWYAAAAMYXV4bAAAAAEAAAAkZWR0cwAAABxlbHN0AAAAAQAAAAEAAAAeAAAAAAAB" +
        "AAAAAAJrbWV0YQAAAAAAAAAhaGRscgAAAAAAAAAAcGljdAAAAAAAAAAAAAAAAAAAAAA0aWxvYwAAAABEQAACAAEAAAAACG8AAQAAAAAAAACYAAIAAAAACQcA" +
        "AQAAAAAAAACuAAAAOGlpbmYAAAAAAAIAAAAVaW5mZQIAAAAAAQAAaHZjMQAAAAAVaW5mZQIAAAAAAgAAaHZjMQAAAAAOcGl0bQAAAAAAAQAAAappcHJwAAAB" +
        "gmlwY28AAAB2aHZjQwEDcAAAAAAAAAAAAB7wAPz9+PgAAA8DYAABABhAAQwB//8DcAAAAwCQAAADAAADAB66AkBhAAEAKkIBAQNwAAADAJAAAAMAAAMAHqAg" +
        "gQWW6uSmubgIaDAgAAADAyAAAAMAIWIAAQAGRAHBc8CJAAAAE2NvbHJuY2x4AAEADQAGgAAAABRpc3BlAAAAAAAAAEAAAABAAAAAKGNsYXAAAABAAAAAAQAA" +
        "ADAAAAABAAAAAAAAAAL////wAAAAAgAAABBwaXhpAAAAAAMICAgAAABwaHZjQwEECAAAAAAAAAAAAB7wAPz8+PgAAA8DYAABABdAAQwB//8ECAAAAwCf+AAA" +
        "AwAAHroCQGEAAQAlQgEBBAgAAAMAn/gAAAMAAB7AggQWW6uSmubAgAAADIAAAAMAhGIAAQAGRAHBc8CJAAAADnBpeGkAAAAAAQgAAAAnYXV4QwAAAAB1cm46" +
        "bXBlZzpoZXZjOjIwMTU6YXV4aWQ6MQAAAAAgaXBtYQAAAAAAAAACAAEFgQIDBYQAAgWGAweIhAAAABppcmVmAAAAAAAAAA5hdXhsAAIAAQABAAABTm1kYXQA" +
        "AACUKAGvBjiJ8sPpv+r8CGqlf5u2n//7LZ/Zf5MM6vympmHynMr19W/h79/3v+xYH1DwnTt58fqDTGG0goFXchpw3s7CQC7lu5COQVyUWjODBqnbf1P3A1df" +
        "uJdtEgPg4tm7DBjj2MhErsP4ajeL8P4CCqXnVupGB8TUtuuv49jca3pNK82V/Rv70AQy43EWJGMuvO1CgAAAAKooAa4McLUL4X/hLX5Lq/6l64593cYJyv1N" +
        "ps6svG4cJ3iFvVTntZZzQd+N/dkKcQtvAstwT4I4batSeg1OufPdGoNSQ69T3zn/zQRh0PRnvuNdlG9+/oYs+st0anvOpIdiZV5sGYlEW6Az99AyUvNZVKnm" +
        "2ryijzgwT6Z4yuJtLx9TvqeEMuQ1FPFx3Z7/r/mo2vkfzLzLjP/vQAHfG54v4Ss8YlivrR+LYAAAAfNtZGF0AAAAlCgBrwa4kcWbSf+1vs9QG37Mhx//9Ixb" +
        "yH9i8ccEm86tn85aOkpIugo4mfk2sA84iE1nNWdmaQaLt3wgzB+Wpm9vPRFm32nYQ4XOxua8PRd4x4/olCDV1+43JZGYpdJbN2GC2PsZEQXYfx3DL+3275Rk" +
        "ZX3fSMD5Lpbddf2KePwZZE9gNyBj/3oCTlxuIsSMZdednvgAAABYAgHQCX4RGDXAFSgUS8cN4vx6cZV76LAZPdCf4f8j8H4H3cdMdF8H70T2E8puhyTxbAzo" +
        "Q+gr5jNpKaZGreVe12R36m37bz0/9yt2RHgwwvuhq5e5LXM4gAAAAB0qAawI9cOoV4YDk6/73fF3v+io7//k2DX3GIk/fAAAAKooAa4NcLvWk/9rfj8Bt/nd" +
        "++dSuqdaQgmKqK5tu16lsU6rwO4HvrrGFX3KC+pwnwwr2a9GAiky8YiDwxrisuBib1nszq1uK1g/1M5nlDxm1mOMyih0ayE8+vt0kFLK7yj7Jzzn3rvoF+R/" +
        "+OtmQ/nPVvWrLCWMk1l9l7V3yuJtLx9T8B9tsIIQMAZfzn6O6Oyhf/I/mXmXGf/kq9sWs0Vb0xUPJVl7h0HBwAAAABMCAdAJfCDBrohPoD/eD4nVVwz4AAAA" +
        "DQIB0BH/qIGDVKrkyNI=";
}