<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="SkiaSharp" Version="4.150.1" />
      <PackageReference Include="Svg.Skia" Version="5.1.1" />
    </ItemGroup>

    <ItemGroup>
        <EmbeddedResource Include="Resources\Icons\**\*.svg" />
    </ItemGroup>
    
</Project>
