namespace Lyra.Imaging.Tests.Support;

/// <summary>
/// Small real HEIF and AVIF still images, made with heif-enc from 64x48 PNGs. Unless noted the
/// picture is red on the left half and blue on the right.
/// </summary>
internal static class HeifStillFixtures
{
    /// <summary>AV1, lossless RGB, tagged Display-P3 through NCLX (primaries 12, sRGB transfer).</summary>
    public const string AvifDisplayP3 =
        "AAAAHGZ0eXBhdmlmAAAAAG1pZjFhdmlmbWlhZgAAAYRtZXRhAAAAAAAAACFoZGxyAAAAAAAAAABwaWN0AAAAAAAAAAAAAAAAAAAAADRpbG9jAAAAAERAAAIA" +
        "AQAAAAABqAABAAAAAAAAAHQAAgAAAAACHAABAAAAAAAAABgAAAA4aWluZgAAAAAAAgAAABVpbmZlAgAAAAABAABhdjAxAAAAABVpbmZlAgAAAAACAABhdjAx" +
        "AAAAAA5waXRtAAAAAAABAAAAw2lwcnAAAACdaXBjbwAAAAxhdjFDgSACAAAAABNjb2xybmNseAAMAA0AAIAAAAAUaXNwZQAAAAAAAABAAAAAMAAAABBwaXhp" +
        "AAAAAAMICAgAAAAMYXYxQ4EAHAAAAAAOcGl4aQAAAAABCAAAADhhdXhDAAAAAHVybjptcGVnOm1wZWdCOmNpY3A6c3lzdGVtczphdXhpbGlhcnk6YWxwaGEA" +
        "AAAAHmlwbWEAAAAAAAAAAgABBIECAwQAAgSFAwaHAAAAGmlyZWYAAAAAAAAADmF1eGwAAgABAAEAAACUbWRhdBIACgk4FX+9hDA0AkAyZRAAALRRtPDE84EZ" +
        "Aebval9E0HkXxf2Xt7wpuhW1fluWtDAufY0Ad8xV3ZZAZlu9OTzXfsF2rZiBd21AMnk5LVlIIEU+b7lUSuZYhyZWE5Vvn/S8iMgiZozw1FS+D42HbSGoWt1Q" +
        "EgAKBhgVf72FQDIMEAC0VANo/xpg+dTA";

    /// <summary>HEVC carrying macOS's Adobe RGB (1998) ICC profile; coded at 64x64 and cropped to 64x48.</summary>
    public const string HeicAdobeRgb =
        "AAAAHGZ0eXBoZWljAAAAAG1pZjFoZWljbWlhZgAABJRtZXRhAAAAAAAAACFoZGxyAAAAAAAAAABwaWN0AAAAAAAAAAAAAAAAAAAAADRpbG9jAAAAAERAAAIA" +
        "AQAAAAAEuAABAAAAAAAAAI4AAgAAAAAFRgABAAAAAAAAABMAAAA4aWluZgAAAAAAAgAAABVpbmZlAgAAAAABAABodmMxAAAAABVpbmZlAgAAAAACAABodmMx" +
        "AAAAAA5waXRtAAAAAAABAAAD02lwcnAAAAOraXBjbwAAAHZodmNDAQNwAAAAAAAAAAAAHvAA/P34+AAADwNgAAEAGEABDAH//wNwAAADAJAAAAMAAAMAHroC" +
        "QGEAAQAqQgEBA3AAAAMAkAAAAwAAAwAeoCCBBZbq5Ka5uAhoMCAAAAMDIAAAAwAhYgABAAZEAcFzwIkAAAI8Y29scnByb2YAAAIwQURCRQIQAABtbnRyUkdC" +
        "IFhZWiAH0AAIAAsAEwAzADthY3NwQVBQTAAAAABub25lAAAAAAAAAAAAAAAAAAAAAAAA9tYAAQAAAADTLUFEQkUAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAApjcHJ0AAAA/AAAADJkZXNjAAABMAAAAGt3dHB0AAABnAAAABRia3B0AAABsAAAABRyVFJDAAABxAAAAA5nVFJDAAAB" +
        "1AAAAA5iVFJDAAAB5AAAAA5yWFlaAAAB9AAAABRnWFlaAAACCAAAABRiWFlaAAACHAAAABR0ZXh0AAAAAENvcHlyaWdodCAyMDAwIEFkb2JlIFN5c3RlbXMg" +
        "SW5jb3Jwb3JhdGVkAAAAZGVzYwAAAAAAAAARQWRvYmUgUkdCICgxOTk4KQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAWFlaIAAAAAAAAPNRAAEAAAABFsxYWVogAAAAAAAAAAAAAAAAAAAAAGN1cnYAAAAAAAAAAQIzAABj" +
        "dXJ2AAAAAAAAAAECMwAAY3VydgAAAAAAAAABAjMAAFhZWiAAAAAAAACcGAAAT6UAAAT8WFlaIAAAAAAAADSNAACgLAAAD5VYWVogAAAAAAAAJjEAABAvAAC+" +
        "nAAAABRpc3BlAAAAAAAAAEAAAABAAAAAKGNsYXAAAABAAAAAAQAAADAAAAABAAAAAAAAAAL////wAAAAAgAAABBwaXhpAAAAAAMICAgAAABwaHZjQwEECAAA" +
        "AAAAAAAAAB7wAPz8+PgAAA8DYAABABdAAQwB//8ECAAAAwCf+AAAAwAAHroCQGEAAQAlQgEBBAgAAAMAn/gAAAMAAB7AggQWW6uSmubAgAAADIAAAAMAhGIA" +
        "AQAGRAHBc8CJAAAADnBpeGkAAAAAAQgAAAAnYXV4QwAAAAB1cm46bXBlZzpoZXZjOjIwMTU6YXV4aWQ6MQAAAAAgaXBtYQAAAAAAAAACAAEFgQIDBYQAAgWG" +
        "AweIhAAAABppcmVmAAAAAAAAAA5hdXhsAAIAAQABAAAAqW1kYXQAAACKKAGvBjiJLnwv9qNf//+y2f2X+TDkppl/j6Fcj/lWI///jMam/8BOzRP1slDVnJe7" +
        "BHTGGW16jl4sVIjNAH8D2Ql2q0A2UdiuzY9WWsoP4ETGtx4RYFBzqHZ+wAYNMuDmpRXUcOTnGpK1nXPwksOOTbvSqZej2pO+noHNV/f3oCmVEGJKWz0hoRHA" +
        "AAAADygBrgxwtQvLf+Dl/sVfEw==";

    /// <summary>HEVC, transparent on the left half and green on the right, with a 16x12 thumbnail and EXIF Make "Lyra", Model "Fixture".</summary>
    public const string HeicThumbnailAndExif =
        "AAAAHGZ0eXBoZWljAAAAAG1pZjFoZWljbWlhZgAABChtZXRhAAAAAAAAACFoZGxyAAAAAAAAAABwaWN0AAAAAAAAAAAAAAAAAAAAAGppbG9jAAAAAERAAAUA" +
        "AQAAAAAElgABAAAAAAAAALQAAgAAAAAFSgABAAAAAAAAAK4AAwAAAAAF+AABAAAAAAAAAFAABAAAAAAGSAABAAAAAAAAADsABQAAAAAAAAABAAAETAAAAEoA" +
        "AAB3aWluZgAAAAAABQAAABVpbmZlAgAAAAABAABodmMxAAAAABVpbmZlAgAAAAACAABodmMxAAAAABVpbmZlAgAAAAADAABodmMxAAAAABVpbmZlAgAAAAAE" +
        "AABodmMxAAAAABVpbmZlAgAAAQAFAABFeGlmAAAAAA5waXRtAAAAAAABAAACyGlwcnAAAAKQaXBjbwAAAHZodmNDAQNwAAAAAAAAAAAAHvAA/P34+AAADwNg" +
        "AAEAGEABDAH//wNwAAADAJAAAAMAAAMAHroCQGEAAQAqQgEBA3AAAAMAkAAAAwAAAwAeoCCBBZbq5Ka5uAhoMCAAAAMDIAAAAwAhYgABAAZEAcFzwIkAAAAT" +
        "Y29scm5jbHgAAQANAAaAAAAAFGlzcGUAAAAAAAAAQAAAAEAAAAAoY2xhcAAAAEAAAAABAAAAMAAAAAEAAAAAAAAAAv////AAAAACAAAAEHBpeGkAAAAAAwgI" +
        "CAAAAHBodmNDAQQIAAAAAAAAAAAAHvAA/Pz4+AAADwNgAAEAF0ABDAH//wQIAAADAJ/4AAADAAAeugJAYQABACVCAQEECAAAAwCf+AAAAwAAHsCCBBZbq5Ka" +
        "5sCAAAAMgAAAAwCEYgABAAZEAcFzwIkAAAAOcGl4aQAAAAABCAAAACdhdXhDAAAAAHVybjptcGVnOmhldmM6MjAxNTphdXhpZDoxAAAAAHVodmNDAQNwAAAA" +
        "AAAAAAAAHvAA/P34+AAADwNgAAEAGEABDAH//wNwAAADAJAAAAMAAAMAHroCQGEAAQApQgEBA3AAAAMAkAAAAwAAAwAeoCCBBZbqrprm4CGgwIAAAAyAAAAD" +
        "AIRiAAEABkQBwXPBiQAAAChjbGFwAAAAEAAAAAEAAAAMAAAAAf///9AAAAAC////zAAAAAIAAABxaHZjQwEECAAAAAAAAAAAAB7wAPz8+PgAAA8DYAABABdA" +
        "AQwB//8ECAAAAwCf+AAAAwAAHroCQGEAAQAmQgEBBAgAAAMAn/gAAAMAAB7AggQWW6q6a5sCAAADADIAAAMAAhBiAAEABkQBwXPBiQAAADBpcG1hAAAAAAAA" +
        "AAQAAQWBAgMFhAACBYYDB4iEAAMFiQIDBYoABAWLAweIigAAAERpcmVmAAAAAAAAAA5hdXhsAAIAAQABAAAADmF1eGwABAABAAMAAAAOdGhtYgADAAEAAQAA" +
        "AA5jZHNjAAUAAQABAAACP21kYXQAAAAGRXhpZgAATU0AKgAAAAgAAwEPAAIAAAAFAAAAMgEQAAIAAAAIAAAAOAITAAMAAAABAAEAAAAAAABMeXJhAABGaXh0" +
        "dXJlAAAAALAoAa8GOInyw+m/6vwIaqV/zMSf//9j0///9/zOr8pqZh671g5tKXsjVkD9rtMnnqjUhg0qqZLjp2olBjpvqaAW9tKDBlJedK8b4hWFDgd9AXxS" +
        "fuqurD6wrPFg5QVBFoAcLCnYKbkM0IbGZsCl6TgpiyRqt+AeC9YtP4ajdRkhyNiCbXEq9vSTKH9cVGY/I5w2I20JSQuGRPMZ31Qg+g0/3n6sZvonrXQeSs5e" +
        "tzmhQAAAAKooAa4McLUL4X/hLX5Lq/6l64593cYJyv1Nps6svG4cJ3iFvVTntZZzQd+N/dkKcQtvAstwT4I4batSeg1OufPdGoNSQ69T3zn/zQRh0PRnvuNd" +
        "lG9+/oYs+st0anvOpIdiZV5sGYlEW6Az99AyUvNZVKnm2ryijzgwT6Z4yuJtLx9TvqeEMuQ1FPFx3Z7/r/mo2vkfzLzLjP/vQAHfG54v4Ss8YlivrR+LYAAA" +
        "AEwoAa8GMhrBxoDmsTPJXRN+HXQL/fUcj//2xN//puy6mA7xiNcA5+ls/VWPx8f23/huLkNb29BkawgFZAt/0Fgxtk3MwpRW7NM5PtTAAAAANygBrgxkNAIJ" +
        "dcwnJvvvsXb+wxYAYFGAAHrUffVMtM1MyIi4d5teO0uMh+v3LqJ8m7ktIHq9cCo=";

    /// <summary>AV1, two top-level images: the picture above as primary, then solid green.</summary>
    public const string AvifTwoImages =
        "AAAAHGZ0eXBhdmlmAAAAAG1pZjFhdmlmbWlhZgAAAe5tZXRhAAAAAAAAACFoZGxyAAAAAAAAAABwaWN0AAAAAAAAAAAAAAAAAAAAAFhpbG9jAAAAAERAAAQA" +
        "AQAAAAACEgABAAAAAAAAAHQAAgAAAAAChgABAAAAAAAAABgAAwAAAAACngABAAAAAAAAACgABAAAAAACxgABAAAAAAAAABgAAABiaWluZgAAAAAABAAAABVp" +
        "bmZlAgAAAAABAABhdjAxAAAAABVpbmZlAgAAAAACAABhdjAxAAAAABVpbmZlAgAAAAADAABhdjAxAAAAABVpbmZlAgAAAAAEAABhdjAxAAAAAA5waXRtAAAA" +
        "AAABAAAA0WlwcnAAAACdaXBjbwAAAAxhdjFDgSACAAAAABNjb2xybmNseAABAA0AAIAAAAAUaXNwZQAAAAAAAABAAAAAMAAAABBwaXhpAAAAAAMICAgAAAAM" +
        "YXYxQ4EAHAAAAAAOcGl4aQAAAAABCAAAADhhdXhDAAAAAHVybjptcGVnOm1wZWdCOmNpY3A6c3lzdGVtczphdXhpbGlhcnk6YWxwaGEAAAAALGlwbWEAAAAA" +
        "AAAABAABBIECAwQAAgSFAwaHAAMEgQIDBAAEBIUDBocAAAAoaXJlZgAAAAAAAAAOYXV4bAACAAEAAQAAAA5hdXhsAAQAAQADAAAA1G1kYXQSAAoJOBV/vYQE" +
        "NACAMmUQAAC0UbTwxPOBGQHm72pfRNB5F8X9l7e8KboVtX5blrQwLn2NAHfMVd2WQGZbvTk8137Bdq2YgXdtQDJ5OS1ZSCBFPm+5VErmWIcmVhOVb5/0vIjI" +
        "ImaM8NRUvg+Nh20hqFrdUBIACgYYFX+9hUAyDBAAtFQDaP8aYPnUwBIACgk4FX+9hAQ0AIAyGRAAALRRs+wBOmIEokSqdl9WqdzBQ1JwwTMSAAoGGBV/vYVA" +
        "MgwQALRUA2j/GmD51MA=";
}