<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <AssemblyName>LyraViewer</AssemblyName>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <RootNamespace>Lyra</RootNamespace>
    <ApplicationIcon>Resources\AppIcon.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="SDL3-CS" Version="3.4.12.3" />
    <PackageReference Include="SDL3-CS.Native" Version="3.4.2" />
    <PackageReference Include="SkiaSharp" Version="4.150.1" />
    <PackageReference Include="SkiaSharp.NativeAssets.Linux" Version="4.150.1" />
    <PackageReference Include="Svg.Skia" Version="5.1.1" />
    <PackageReference Include="System.IO.Hashing" Version="10.0.10" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Lyra.Common\Lyra.Common.csproj" />
    <ProjectReference Include="..\Lyra.Imaging\Lyra.Imaging.csproj" />
    <ProjectReference Include="..\Lyra.UI\Lyra.UI.csproj" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Resources\AppIcon.png">
      <LogicalName>LyraViewer.AppIcon.png</LogicalName>
    </EmbeddedResource>
  </ItemGroup>

</Project>
