<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <AssemblyName>LyraViewer</AssemblyName>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <RootNamespace>Lyra</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="SDL3-CS" Version="3.4.10.5" />
    <PackageReference Include="SDL3-CS.Native" Version="3.4.2" />
    <PackageReference Include="SkiaSharp" Version="4.148.0" />
    <PackageReference Include="SkiaSharp.NativeAssets.Linux" Version="4.148.0" />
    <PackageReference Include="Svg.Skia" Version="5.1.1" />
    <PackageReference Include="System.IO.Hashing" Version="10.0.9" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Lyra.Common\Lyra.Common.csproj" />
    <ProjectReference Include="..\Lyra.Imaging\Lyra.Imaging.csproj" />
    <ProjectReference Include="..\Lyra.UI\Lyra.UI.csproj" />
  </ItemGroup>
  
</Project>
